# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

ci_config: &ci_config
 - '.github/**'

files_in_root: &files_in_root
 - '*!(/)' # changes in the root, such as cspell.json or pnpm-lock.yaml
 - '.*'

slint:
 - 'api/**'
 - 'cmake/**'
 - 'demos/**'
 - 'docker/**'
 - 'docs/**'
 - 'editors/**'
 - 'examples/**'
 - 'helper_crates/**'
 - 'internal/**'
 - 'logo/**'
 - 'scripts/**'
 - 'tests/**'
 - 'tools/compiler/**'
 - 'tools/docsnapper/**'
 - 'tools/figma_import/**'
 - 'tools/lsp/**'
 - 'tools/slintpad/**'
 - 'tools/tr-extractor/**'
 - 'tools/updater/**'
 - 'tools/viewer/**'
 - 'xtask/**'
 - *files_in_root
 - *ci_config

figma_inspector:
 - 'tools/figma-inspector/**'
 - *files_in_root
 - *ci_config

material_components:
 - 'ui-libraries/material/**'
 - *files_in_root
 - *ci_config

internal: &internal
 - 'internal/**'
 - 'helper_crates/**'
 - *files_in_root
 - *ci_config

api_cpp:
 - 'api/cpp/**'
 - 'tools/compiler/**'

api_python:
 - 'api/python/**'

api_node:
 - 'api/node/**'

api_rs:
 - 'api/rs/**'

tests:
 - 'tests/**'

examples:
 - 'examples/**'
 - 'demos/**'

vsce:
 - *files_in_root
 - *ci_config
 - *internal
 - 'api/rs/**'
 - 'editors/vscode/**'
 - 'tools/lsp/**'
 - 'docs/common/src/utils/slint.tmLanguage.json'

slintpad:
 - *internal
 - 'tools/slintpad/**'
 - 'api/wasm-interpreter/**'
 - 'tools/lsp/**'
 - 'api/rs/**'
 - 'docs/common/src/utils/slint.tmLanguage.json'

updater_test:
 - *internal
 - 'tests/cases/**'
 - 'tools/updater/**'
